### ISSUE TITLE
有对 Linux 做支持吗？

### ISSUE THREAD

**Issue by taotieren** [wh201906/mEDIFIER#2]

**Comment by wh201906** [comment]
目前还没有，手上没有支持蓝牙的Linux环境。后期可能会添加对Linux平台的支持。

**Comment by glpnk** [comment]
I've compiled app for Linux and it works perfectly. I remember that you need to install `qtconnectivity5-dev` package (name of apt package) and basic qt related stuff. Then usage of `qmake` and `make` worked for me

**Comment by wh201906** [comment]
@glpnk Thanks for your feedback

**Comment by taotieren** [comment]
https://aur.archlinux.org/packages/medifier-git

**Comment by wh201906** [comment]
@taotieren 非常感谢

**Comment by wh201906** [comment]
@taotieren 你好，请问你是不是把metadata给弄错了？
```
<component type="desktop-application">
  <id>io.github.skiars.medifier</id>

  <name>medifier</name>
  <summary>medifier</summary>

  <metadata_license>CC-BY-SA-4.0</metadata_license>
  <project_license>MIT</project_license>

  <description>
    <p>
      I just don't know why the Edifier Connect takes up more than 200MB on my phone.
    </p>
  </description>

  <launchable type="desktop-id">io.github.skiars.medifier.desktop</launchable>
</component>
```
包名那里为什么是`io.github.skiars`呢？

**Comment by wh201906** [comment]
@taotieren 我已经修改过来了，现在metadata位于本仓库的`deploy/aur/`下。如果有什么配置错误的地方还请指正，谢谢

**Comment by taotieren** [comment]
应该是之前改的时候漏掉了
下次更新的时候同步修改下
谢谢
