### ISSUE TITLE
dev: "" "00:00:00:00:00:00" (:0)

### ISSUE THREAD

**Issue by n30f0x** [wh201906/mEDIFIER#6]
looks like implementation of permission acquiring mechanism is incorrect 

S22ultra, oneui 6.1, android 14 renders next logs

QObject::connect: Cannot queue arguments of type 'QItemSelection'
(Make sure 'QItemSelection' is registered using qRegisterMetaType().) (:0, )
QBasicTimer::start: Timers cannot be started from another thread (:0, )
QObject::startTimer: Timers can only be used with threads started with QThread (:0, )
QObject::killTimer: Timers cannot be stopped from another thread (:0, )
QBasicTimer::start: Timers cannot be started from another thread (:0, )
dev: "" "00:00:00:00:00:00" (:0, )
Falling back to reverse uuid workaround. (:0, )

**Comment by wh201906** [comment]
Please try the latest release to see if the bug is fixed.

**Comment by n30f0x** [comment]
at last, it works!
may i use your work to add headphone support in gadgetbridge?

also I'm unable to set name, looks like packet is ignored as i see hex sent in logs:
send: "aa11ca666f787869652d6d7573696370617773283a" (:0, )

thank you for amazing work <3

**Comment by wh201906** [comment]
> may i use your work to add headphone support in gadgetbridge?

Yes, you may. It would be better if you can mention the source of the raw commands as the reference for others.
https://github.com/wh201906/mEDIFIER/blob/main/doc/KnownCommands/W820NB_Double_Gold.txt

> looks like packet is ignored.

Are you using W820NB Double Gold? I can set the name of it with mEDIFIER.

**Comment by n30f0x** [comment]
> Are you using W820NB Double Gold? I can set the name of it with mEDIFIER.

I'm owner of w820nb plus (mint color, but looks like chip is same, tried to reverse engineer it on my own)

**Comment by wh201906** [comment]
I don't know why it doesn't work...

**Comment by n30f0x** [comment]
if you tell me what i could do maybe i could help you somehow? i have ability to monitor and create bluetooth packets and fair bit of hardware equipment (cmsis-dap)

**Comment by wh201906** [comment]
Would you mind installing the official Edifier Connect app? You can check the raw Bluetooth packets of it in the Logcat. When setting a name to your device, the corresponding packets will be shown in the log.

**Comment by n30f0x** [comment]
as i have no issues with name anymore (re-paired few times and it seems to work now) i'm closing thread, again, thank you for amazing work <3
