### ISSUE TITLE
MacOS and Linux support

### ISSUE THREAD

**Issue by datdadev** [wh201906/mEDIFIER#8]
Can you develop this for MacOS and Linux operating system also?

**Comment by wh201906** [comment]
I don't have physical macOS or Linux devices so I cannot test if this app is working on these platforms.
However, the Qt Bluetooth module is cross-platform, so you could try to compile it on your preferred platform and check if it's working.

**Comment by leleobhz** [comment]
> I don't have physical macOS or Linux devices so I cannot test if this app is working on these platforms. However, the Qt Bluetooth module is cross-platform, so you could try to compile it on your preferred platform and check if it's working.

Hello!

![image](https://github.com/user-attachments/assets/4ce652fb-2cee-486d-8f1f-7c204b66f679)

On CachyOS from AUR, it works properly. Thank you for this code!

**Comment by leleobhz** [comment]
P.s:

> The BLE connection on Windows hardly works

Hardly works on Linux too. It's a matter of luck (+- 1/5 attempts) to get connected. Also, it disconnects from BLE if you change LDAC rate as same it does (Obviously) with RFCOMM . 

BT controller on my machine is `Bus 001 Device 006: ID 8087:0029 Intel Corp. AX200 Bluetooth`

**Comment by Lefox-DeMod** [comment]
> P.s:
> 
> > The BLE connection on Windows hardly works
> 
> Hardly works on Linux too. It's a matter of luck (+- 1/5 attempts) to get connected. Also, it disconnects from BLE if you change LDAC rate as same it does (Obviously) with RFCOMM .
> 
> BT controller on my machine is `Bus 001 Device 006: ID 8087:0029 Intel Corp. AX200 Bluetooth`

Perfectly works on linux with wn820nb plus. All function works correctly just like on android version.

![Image](https://github.com/user-attachments/assets/5ada4894-ec33-47c3-ae4d-f985077479b2)
BT controller: `08:00.0 Network controller: MEDIATEK Corp. MT7922 802.11ax PCI Express Wireless Network Adapter`

**Comment by leleobhz** [comment]
Hello!

> Perfectly works on linux with wn820nb plus. All function works correctly just like on android version.

Are you using BLE or RFCOMM? RFCOMM worked flawless with me and this report is just to confirm BLE is unstable.

**Comment by Lefox-DeMod** [comment]
> Hello!
> 
> > Perfectly works on linux with wn820nb plus. All function works correctly just like on android version.
> 
> Are you using BLE or RFCOMM? RFCOMM worked flawless with me and this report is just to confirm BLE is unstable.

I'm using RFCOMM
